// ----------------------------------------------------------------------------
//
//     ***     AUTO GENERATED CODE    ***    Type: MMv1     ***
//
// ----------------------------------------------------------------------------
//
//     This file is automatically generated by Magic Modules and manual
//     changes will be clobbered when the file is regenerated.
//
//     Please read more about how to change this file in
//     .github/CONTRIBUTING.md.
//
// ----------------------------------------------------------------------------

package kms

import (
	"fmt"

	"github.com/GoogleCloudPlatform/terraform-google-conversion/v6/tfplan2cai/converters/google/resources/cai"
	"github.com/hashicorp/terraform-provider-google-beta/google-beta/tpgresource"
	transport_tpg "github.com/hashicorp/terraform-provider-google-beta/google-beta/transport"
)

// Provide a separate asset type constant so we don't have to worry about name conflicts between IAM and non-IAM converter files
const KMSEkmConnectionIAMAssetType string = "cloudkms.googleapis.com/EkmConnection"

func ResourceConverterKMSEkmConnectionIamPolicy() cai.ResourceConverter {
	return cai.ResourceConverter{
		AssetType:         KMSEkmConnectionIAMAssetType,
		Convert:           GetKMSEkmConnectionIamPolicyCaiObject,
		MergeCreateUpdate: MergeKMSEkmConnectionIamPolicy,
	}
}

func ResourceConverterKMSEkmConnectionIamBinding() cai.ResourceConverter {
	return cai.ResourceConverter{
		AssetType:         KMSEkmConnectionIAMAssetType,
		Convert:           GetKMSEkmConnectionIamBindingCaiObject,
		FetchFullResource: FetchKMSEkmConnectionIamPolicy,
		MergeCreateUpdate: MergeKMSEkmConnectionIamBinding,
		MergeDelete:       MergeKMSEkmConnectionIamBindingDelete,
	}
}

func ResourceConverterKMSEkmConnectionIamMember() cai.ResourceConverter {
	return cai.ResourceConverter{
		AssetType:         KMSEkmConnectionIAMAssetType,
		Convert:           GetKMSEkmConnectionIamMemberCaiObject,
		FetchFullResource: FetchKMSEkmConnectionIamPolicy,
		MergeCreateUpdate: MergeKMSEkmConnectionIamMember,
		MergeDelete:       MergeKMSEkmConnectionIamMemberDelete,
	}
}

func GetKMSEkmConnectionIamPolicyCaiObject(d tpgresource.TerraformResourceData, config *transport_tpg.Config) ([]cai.Asset, error) {
	return newKMSEkmConnectionIamAsset(d, config, cai.ExpandIamPolicyBindings)
}

func GetKMSEkmConnectionIamBindingCaiObject(d tpgresource.TerraformResourceData, config *transport_tpg.Config) ([]cai.Asset, error) {
	return newKMSEkmConnectionIamAsset(d, config, cai.ExpandIamRoleBindings)
}

func GetKMSEkmConnectionIamMemberCaiObject(d tpgresource.TerraformResourceData, config *transport_tpg.Config) ([]cai.Asset, error) {
	return newKMSEkmConnectionIamAsset(d, config, cai.ExpandIamMemberBindings)
}

func MergeKMSEkmConnectionIamPolicy(existing, incoming cai.Asset) cai.Asset {
	existing.IAMPolicy = incoming.IAMPolicy
	return existing
}

func MergeKMSEkmConnectionIamBinding(existing, incoming cai.Asset) cai.Asset {
	return cai.MergeIamAssets(existing, incoming, cai.MergeAuthoritativeBindings)
}

func MergeKMSEkmConnectionIamBindingDelete(existing, incoming cai.Asset) cai.Asset {
	return cai.MergeDeleteIamAssets(existing, incoming, cai.MergeDeleteAuthoritativeBindings)
}

func MergeKMSEkmConnectionIamMember(existing, incoming cai.Asset) cai.Asset {
	return cai.MergeIamAssets(existing, incoming, cai.MergeAdditiveBindings)
}

func MergeKMSEkmConnectionIamMemberDelete(existing, incoming cai.Asset) cai.Asset {
	return cai.MergeDeleteIamAssets(existing, incoming, cai.MergeDeleteAdditiveBindings)
}

func newKMSEkmConnectionIamAsset(
	d tpgresource.TerraformResourceData,
	config *transport_tpg.Config,
	expandBindings func(d tpgresource.TerraformResourceData) ([]cai.IAMBinding, error),
) ([]cai.Asset, error) {
	bindings, err := expandBindings(d)
	if err != nil {
		return []cai.Asset{}, fmt.Errorf("expanding bindings: %v", err)
	}

	name, err := cai.AssetName(d, config, "//cloudkms.googleapis.com/projects/{{project}}/locations/{{location}}/ekmConnections/{{name}}")
	if err != nil {
		return []cai.Asset{}, err
	}

	return []cai.Asset{{
		Name: name,
		Type: KMSEkmConnectionIAMAssetType,
		IAMPolicy: &cai.IAMPolicy{
			Bindings: bindings,
		},
	}}, nil
}

func FetchKMSEkmConnectionIamPolicy(d tpgresource.TerraformResourceData, config *transport_tpg.Config) (cai.Asset, error) {
	// Check if the identity field returns a value
	if _, ok := d.GetOk("location"); !ok {
		return cai.Asset{}, cai.ErrEmptyIdentityField
	}
	if _, ok := d.GetOk("name"); !ok {
		return cai.Asset{}, cai.ErrEmptyIdentityField
	}

	return cai.FetchIamPolicy(
		KMSEkmConnectionIamUpdaterProducer,
		d,
		config,
		"//cloudkms.googleapis.com/projects/{{project}}/locations/{{location}}/ekmConnections/{{name}}",
		KMSEkmConnectionIAMAssetType,
	)
}
