// ----------------------------------------------------------------------------
//
//     ***     AUTO GENERATED CODE    ***    Type: MMv1     ***
//
// ----------------------------------------------------------------------------
//
//     This file is automatically generated by Magic Modules and manual
//     changes will be clobbered when the file is regenerated.
//
//     Please read more about how to change this file in
//     .github/CONTRIBUTING.md.
//
// ----------------------------------------------------------------------------

// Package cloudfunctions2 contains resources, datasources, etc. for the cloud functions (2nd gen) service.
package cloudfunctions2

import (
	"github.com/GoogleCloudPlatform/terraform-google-conversion/v7/pkg/registry"
)

var Product = registry.Product{
	Name:                 "cloudfunctions2",
	BaseUrl:              "https://cloudfunctions.googleapis.com/v2/",
	CustomEndpointField:  "cloudfunctions2_custom_endpoint",
	CustomEndpointEnvVar: "GOOGLE_CLOUDFUNCTIONS2_CUSTOM_ENDPOINT",
}

func init() {
	Product.Register()
}
