// ----------------------------------------------------------------------------
//
//     ***     AUTO GENERATED CODE    ***    Type: MMv1     ***
//
// ----------------------------------------------------------------------------
//
//     This file is automatically generated by Magic Modules and manual
//     changes will be clobbered when the file is regenerated.
//
//     Please read more about how to change this file in
//     .github/CONTRIBUTING.md.
//
// ----------------------------------------------------------------------------

package compute_test

import (
	"os"
	"testing"

	"github.com/GoogleCloudPlatform/terraform-google-conversion/v7/test"
)

func TestAccComputeAddress(t *testing.T) {
	if os.Getenv("WRITE_FILES") != "" {
		t.Parallel()
	}
	tests := []test.TestCase{
		{
			Name: "TestAccComputeAddress_addressBasicExample",
		},
		{
			Name: "TestAccComputeAddress_addressWithSubnetworkExample",
		},
		{
			Name: "TestAccComputeAddress_addressWithGceEndpointExample",
		},
		{
			Name: "TestAccComputeAddress_addressWithSharedLoadbalancerVipExample",
		},
		{
			Name: "TestAccComputeAddress_instanceWithIpExample",
		},
		{
			Name: "TestAccComputeAddress_computeAddressIpsecInterconnectExample",
		},
		{
			Name: "TestAccComputeAddress_computeAddressEnhancedByoipExample",
			Skip: "fix later",
		},
		{
			Name: "TestAccComputeAddress_networkTier",
		},
		{
			Name: "TestAccComputeAddress_internal",
		},
		{
			Name: "TestAccComputeAddress_networkTier_withLabels",
		},
		{
			Name: "TestAccComputeAddress_networkTier_withProvider5",
		},
		{
			Name: "TestAccComputeAddress_withProviderDefaultLabels",
		},
		{
			Name: "TestAccComputeAddress_withCreationOnlyAttribution",
		},
		{
			Name: "TestAccComputeAddress_withCreationOnlyAttributionSetOnUpdate",
		},
		{
			Name: "TestAccComputeAddress_withProactiveAttribution",
		},
		{
			Name: "TestAccComputeAddress_withProactiveAttributionSetOnUpdate",
		},
		{
			Name: "TestAccComputeAddress_withAttributionRemoved",
		},
		{
			Name: "TestAccComputeAddress_internalIpv6",
		},
	}

	for _, tt := range tests {
		tt := tt

		t.Run(tt.Name, func(t *testing.T) {
			t.Parallel()

			if tt.Skip != "" {
				t.Skipf("Skipping %s test case: This case is currently disabled due to Issue.", tt.Name)
			}

			test.BidirectionalConversion(
				t,
				[]string{
					"count",
					"depends_on",
					"for_each",
					"lifecycle",
					"provider",
					"timeouts",
				},
				"google_compute_address",
			)
		})
	}
}
