// ----------------------------------------------------------------------------
//
//     ***     AUTO GENERATED CODE    ***    Type: MMv1     ***
//
// ----------------------------------------------------------------------------
//
//     This file is automatically generated by Magic Modules and manual
//     changes will be clobbered when the file is regenerated.
//
//     Please read more about how to change this file in
//     .github/CONTRIBUTING.md.
//
// ----------------------------------------------------------------------------

package compute_test

import (
	"os"
	"testing"

	"github.com/GoogleCloudPlatform/terraform-google-conversion/v7/test"
)

func TestAccComputeRegionHealthCheck(t *testing.T) {
	if os.Getenv("WRITE_FILES") != "" {
		t.Parallel()
	}
	tests := []test.TestCase{
		{
			Name: "TestAccComputeRegionHealthCheck_typeTransition",
			Skip: "Test data has mismatched steps",
		},
		{
			Name: "TestAccComputeRegionHealthCheck_grpcWithTls_create",
			Skip: "Test data has mismatched steps",
		},
		{
			Name: "TestAccComputeRegionHealthCheck_grpcWithTls_update",
			Skip: "Test data has mismatched steps",
		},
		{
			Name: "TestAccComputeRegionHealthCheck_regionHealthCheckTcpExample",
		},
		{
			Name: "TestAccComputeRegionHealthCheck_regionHealthCheckTcpFullExample",
		},
		{
			Name: "TestAccComputeRegionHealthCheck_regionHealthCheckSslExample",
		},
		{
			Name: "TestAccComputeRegionHealthCheck_regionHealthCheckSslFullExample",
		},
		{
			Name: "TestAccComputeRegionHealthCheck_regionHealthCheckHttpExample",
		},
		{
			Name: "TestAccComputeRegionHealthCheck_regionHealthCheckHttpFullExample",
		},
		{
			Name: "TestAccComputeRegionHealthCheck_regionHealthCheckHttpsExample",
		},
		{
			Name: "TestAccComputeRegionHealthCheck_regionHealthCheckHttpsFullExample",
		},
		{
			Name: "TestAccComputeRegionHealthCheck_regionHealthCheckHttp2Example",
		},
		{
			Name: "TestAccComputeRegionHealthCheck_regionHealthCheckHttp2FullExample",
		},
		{
			Name: "TestAccComputeRegionHealthCheck_regionHealthCheckGrpcExample",
		},
		{
			Name: "TestAccComputeRegionHealthCheck_regionHealthCheckGrpcFullExample",
		},
		{
			Name: "TestAccComputeRegionHealthCheck_regionHealthCheckGrpcWithTlsExample",
			Skip: "grpcTlsHealthCheck is not in CAI asset, but is required in this test.",
		},
		{
			Name: "TestAccComputeRegionHealthCheck_regionHealthCheckGrpcWithTlsFullExample",
			Skip: "grpcTlsHealthCheck is not in CAI asset, but is required in this test.",
		},
		{
			Name: "TestAccComputeRegionHealthCheck_tcp_update",
		},
		{
			Name: "",
		},
		{
			Name: "",
		},
		{
			Name: "TestAccComputeRegionHealthCheck_ssl_port_spec",
		},
		{
			Name: "TestAccComputeRegionHealthCheck_http_port_spec",
		},
		{
			Name: "TestAccComputeRegionHealthCheck_https_serving_port",
		},
		{
			Name: "",
		},
		{
			Name: "TestAccComputeRegionHealthCheck_logConfigDisabled",
		},
	}

	for _, tt := range tests {
		tt := tt

		t.Run(tt.Name, func(t *testing.T) {
			t.Parallel()

			if tt.Skip != "" {
				t.Skipf("Skipping %s test case: This case is currently disabled due to Issue.", tt.Name)
			}

			test.BidirectionalConversion(
				t,
				[]string{
					"count",
					"depends_on",
					"for_each",
					"grpc_tls_health_check",
					"lifecycle",
					"provider",
					"timeouts",
				},
				"google_compute_region_health_check",
			)
		})
	}
}
