// ----------------------------------------------------------------------------
//
//     ***     AUTO GENERATED CODE    ***    Type: MMv1     ***
//
// ----------------------------------------------------------------------------
//
//     This code is generated by Magic Modules using the following:
//
//     Configuration: https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/products/compute/PreviewFeature.yaml
//     Template:      https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/tgc/resource_converter.go.tmpl
//
//     DO NOT EDIT this file directly. Any changes made to this file will be
//     overwritten during the next generation cycle.
//
// ----------------------------------------------------------------------------

package compute

import (
	"bytes"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"log"
	"reflect"
	"regexp"
	"slices"
	"sort"
	"strconv"
	"strings"
	"time"

	"github.com/hashicorp/terraform-plugin-sdk/v2/diag"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/customdiff"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/id"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/logging"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/retry"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/structure"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/validation"
	"github.com/hashicorp/terraform-plugin-sdk/v2/terraform"

	"github.com/GoogleCloudPlatform/terraform-google-conversion/v7/tfplan2cai/converters/google/resources/cai"
	"github.com/hashicorp/terraform-provider-google-beta/google-beta/tpgresource"
	transport_tpg "github.com/hashicorp/terraform-provider-google-beta/google-beta/transport"
	"github.com/hashicorp/terraform-provider-google-beta/google-beta/verify"

	"google.golang.org/api/googleapi"
)

var (
	_ = bytes.Clone
	_ = context.WithCancel
	_ = base64.StdEncoding
	_ = fmt.Sprintf
	_ = json.Marshal
	_ = log.Print
	_ = reflect.ValueOf
	_ = regexp.Match
	_ = slices.Min([]int{1})
	_ = sort.IntSlice{}
	_ = strconv.Atoi
	_ = strings.Trim
	_ = time.Now
	_ = diag.Diagnostic{}
	_ = customdiff.All
	_ = id.UniqueId
	_ = logging.LogLevel
	_ = retry.Retry
	_ = schema.Noop
	_ = structure.ExpandJsonFromString
	_ = validation.All
	_ = terraform.State{}
	_ = tpgresource.SetLabels
	_ = transport_tpg.Config{}
	_ = verify.ProjectRegex
	_ = googleapi.Error{}
)

const ComputePreviewFeatureAssetType string = "compute.googleapis.com/PreviewFeature"

func ResourceConverterComputePreviewFeature() cai.ResourceConverter {
	return cai.ResourceConverter{
		AssetType: ComputePreviewFeatureAssetType,
		Convert:   GetComputePreviewFeatureCaiObject,
	}
}

func GetComputePreviewFeatureCaiObject(d tpgresource.TerraformResourceData, config *transport_tpg.Config) ([]cai.Asset, error) {
	name, err := cai.AssetName(d, config, "//compute.googleapis.com/projects/{{project}}/global/previewFeatures/{{name}}")
	if err != nil {
		return []cai.Asset{}, err
	}
	if obj, err := GetComputePreviewFeatureApiObject(d, config); err == nil {
		return []cai.Asset{{
			Name: name,
			Type: ComputePreviewFeatureAssetType,
			Resource: &cai.AssetResource{
				Version:              "beta",
				DiscoveryDocumentURI: "https://www.googleapis.com/discovery/v1/apis/compute/beta/rest",
				DiscoveryName:        "PreviewFeature",
				Data:                 obj,
			},
		}}, nil
	} else {
		return []cai.Asset{}, err
	}
}

func GetComputePreviewFeatureApiObject(d tpgresource.TerraformResourceData, config *transport_tpg.Config) (map[string]interface{}, error) {
	obj := make(map[string]interface{})
	activationStatusProp, err := expandComputePreviewFeatureActivationStatus(d.Get("activation_status"), d, config)
	if err != nil {
		return nil, err
	} else if v, ok := d.GetOkExists("activation_status"); !tpgresource.IsEmptyValue(reflect.ValueOf(activationStatusProp)) && (ok || !reflect.DeepEqual(v, activationStatusProp)) {
		obj["activationStatus"] = activationStatusProp
	}
	rolloutOperationProp, err := expandComputePreviewFeatureRolloutOperation(d.Get("rollout_operation"), d, config)
	if err != nil {
		return nil, err
	} else if v, ok := d.GetOkExists("rollout_operation"); !tpgresource.IsEmptyValue(reflect.ValueOf(rolloutOperationProp)) && (ok || !reflect.DeepEqual(v, rolloutOperationProp)) {
		obj["rolloutOperation"] = rolloutOperationProp
	}

	return obj, nil
}

func expandComputePreviewFeatureActivationStatus(v interface{}, d tpgresource.TerraformResourceData, config *transport_tpg.Config) (interface{}, error) {
	return v, nil
}

func expandComputePreviewFeatureRolloutOperation(v interface{}, d tpgresource.TerraformResourceData, config *transport_tpg.Config) (interface{}, error) {
	if v == nil {
		return nil, nil
	}
	l := v.([]interface{})
	if len(l) == 0 || l[0] == nil {
		return nil, nil
	}
	raw := l[0]
	original := raw.(map[string]interface{})
	transformed := make(map[string]interface{})

	transformedRolloutInput, err := expandComputePreviewFeatureRolloutOperationRolloutInput(original["rollout_input"], d, config)
	if err != nil {
		return nil, err
	} else if val := reflect.ValueOf(transformedRolloutInput); val.IsValid() && !tpgresource.IsEmptyValue(val) {
		transformed["rolloutInput"] = transformedRolloutInput
	}

	return transformed, nil
}

func expandComputePreviewFeatureRolloutOperationRolloutInput(v interface{}, d tpgresource.TerraformResourceData, config *transport_tpg.Config) (interface{}, error) {
	if v == nil {
		return nil, nil
	}
	l := v.([]interface{})
	if len(l) == 0 || l[0] == nil {
		return nil, nil
	}
	raw := l[0]
	original := raw.(map[string]interface{})
	transformed := make(map[string]interface{})

	transformedPredefinedRolloutPlan, err := expandComputePreviewFeatureRolloutOperationRolloutInputPredefinedRolloutPlan(original["predefined_rollout_plan"], d, config)
	if err != nil {
		return nil, err
	} else if val := reflect.ValueOf(transformedPredefinedRolloutPlan); val.IsValid() && !tpgresource.IsEmptyValue(val) {
		transformed["predefinedRolloutPlan"] = transformedPredefinedRolloutPlan
	}

	return transformed, nil
}

func expandComputePreviewFeatureRolloutOperationRolloutInputPredefinedRolloutPlan(v interface{}, d tpgresource.TerraformResourceData, config *transport_tpg.Config) (interface{}, error) {
	return v, nil
}
