// ----------------------------------------------------------------------------
//
//     ***     AUTO GENERATED CODE    ***    Type: MMv1     ***
//
// ----------------------------------------------------------------------------
//
//     This code is generated by Magic Modules using the following:
//
//     Configuration: https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/products/compute/RegionBackendBucket.yaml
//     Template:      https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/tgc/resource_converter_iam.go.tmpl
//
//     DO NOT EDIT this file directly. Any changes made to this file will be
//     overwritten during the next generation cycle.
//
// ----------------------------------------------------------------------------

package compute

import (
	"fmt"

	"github.com/GoogleCloudPlatform/terraform-google-conversion/v7/tfplan2cai/converters/google/resources/cai"
	"github.com/hashicorp/terraform-provider-google-beta/google-beta/tpgresource"
	transport_tpg "github.com/hashicorp/terraform-provider-google-beta/google-beta/transport"
)

// Provide a separate asset type constant so we don't have to worry about name conflicts between IAM and non-IAM converter files
const ComputeRegionBackendBucketIAMAssetType string = "compute.googleapis.com/RegionBackendBucket"

func ResourceConverterComputeRegionBackendBucketIamPolicy() cai.ResourceConverter {
	return cai.ResourceConverter{
		AssetType:         ComputeRegionBackendBucketIAMAssetType,
		Convert:           GetComputeRegionBackendBucketIamPolicyCaiObject,
		MergeCreateUpdate: MergeComputeRegionBackendBucketIamPolicy,
	}
}

func ResourceConverterComputeRegionBackendBucketIamBinding() cai.ResourceConverter {
	return cai.ResourceConverter{
		AssetType:         ComputeRegionBackendBucketIAMAssetType,
		Convert:           GetComputeRegionBackendBucketIamBindingCaiObject,
		FetchFullResource: FetchComputeRegionBackendBucketIamPolicy,
		MergeCreateUpdate: MergeComputeRegionBackendBucketIamBinding,
		MergeDelete:       MergeComputeRegionBackendBucketIamBindingDelete,
	}
}

func ResourceConverterComputeRegionBackendBucketIamMember() cai.ResourceConverter {
	return cai.ResourceConverter{
		AssetType:         ComputeRegionBackendBucketIAMAssetType,
		Convert:           GetComputeRegionBackendBucketIamMemberCaiObject,
		FetchFullResource: FetchComputeRegionBackendBucketIamPolicy,
		MergeCreateUpdate: MergeComputeRegionBackendBucketIamMember,
		MergeDelete:       MergeComputeRegionBackendBucketIamMemberDelete,
	}
}

func GetComputeRegionBackendBucketIamPolicyCaiObject(d tpgresource.TerraformResourceData, config *transport_tpg.Config) ([]cai.Asset, error) {
	return newComputeRegionBackendBucketIamAsset(d, config, cai.ExpandIamPolicyBindings)
}

func GetComputeRegionBackendBucketIamBindingCaiObject(d tpgresource.TerraformResourceData, config *transport_tpg.Config) ([]cai.Asset, error) {
	return newComputeRegionBackendBucketIamAsset(d, config, cai.ExpandIamRoleBindings)
}

func GetComputeRegionBackendBucketIamMemberCaiObject(d tpgresource.TerraformResourceData, config *transport_tpg.Config) ([]cai.Asset, error) {
	return newComputeRegionBackendBucketIamAsset(d, config, cai.ExpandIamMemberBindings)
}

func MergeComputeRegionBackendBucketIamPolicy(existing, incoming cai.Asset) cai.Asset {
	existing.IAMPolicy = incoming.IAMPolicy
	return existing
}

func MergeComputeRegionBackendBucketIamBinding(existing, incoming cai.Asset) cai.Asset {
	return cai.MergeIamAssets(existing, incoming, cai.MergeAuthoritativeBindings)
}

func MergeComputeRegionBackendBucketIamBindingDelete(existing, incoming cai.Asset) cai.Asset {
	return cai.MergeDeleteIamAssets(existing, incoming, cai.MergeDeleteAuthoritativeBindings)
}

func MergeComputeRegionBackendBucketIamMember(existing, incoming cai.Asset) cai.Asset {
	return cai.MergeIamAssets(existing, incoming, cai.MergeAdditiveBindings)
}

func MergeComputeRegionBackendBucketIamMemberDelete(existing, incoming cai.Asset) cai.Asset {
	return cai.MergeDeleteIamAssets(existing, incoming, cai.MergeDeleteAdditiveBindings)
}

func newComputeRegionBackendBucketIamAsset(
	d tpgresource.TerraformResourceData,
	config *transport_tpg.Config,
	expandBindings func(d tpgresource.TerraformResourceData) ([]cai.IAMBinding, error),
) ([]cai.Asset, error) {
	bindings, err := expandBindings(d)
	if err != nil {
		return []cai.Asset{}, fmt.Errorf("expanding bindings: %v", err)
	}

	name, err := cai.AssetName(d, config, "//compute.googleapis.com/projects/{{project}}/regions/{{region}}/backendBuckets/{{name}}")
	if err != nil {
		return []cai.Asset{}, err
	}

	return []cai.Asset{{
		Name: name,
		Type: ComputeRegionBackendBucketIAMAssetType,
		IAMPolicy: &cai.IAMPolicy{
			Bindings: bindings,
		},
	}}, nil
}

func FetchComputeRegionBackendBucketIamPolicy(d tpgresource.TerraformResourceData, config *transport_tpg.Config) (cai.Asset, error) {
	// Check if the identity field returns a value
	if _, ok := d.GetOk("region"); !ok {
		return cai.Asset{}, cai.ErrEmptyIdentityField
	}
	if _, ok := d.GetOk("name"); !ok {
		return cai.Asset{}, cai.ErrEmptyIdentityField
	}

	return cai.FetchIamPolicy(
		ComputeRegionBackendBucketIamUpdaterProducer,
		d,
		config,
		"//compute.googleapis.com/projects/{{project}}/regions/{{region}}/backendBuckets/{{name}}",
		ComputeRegionBackendBucketIAMAssetType,
	)
}
