// ----------------------------------------------------------------------------
//
//     ***     AUTO GENERATED CODE    ***    Type: MMv1     ***
//
// ----------------------------------------------------------------------------
//
//     This file is automatically generated by Magic Modules and manual
//     changes will be clobbered when the file is regenerated.
//
//     Please read more about how to change this file in
//     .github/CONTRIBUTING.md.
//
// ----------------------------------------------------------------------------

// Package modelarmor contains resources, datasources, etc. for the model armor service.
package modelarmor

import (
	"github.com/GoogleCloudPlatform/terraform-google-conversion/v7/pkg/registry"
)

const ProductName = "modelarmor"

func init() {
	registry.Product{
		Name:    "modelarmor",
		BaseUrl: "https://modelarmor.{{location}}.rep.googleapis.com/v1/",
	}.Register()
}
