// ----------------------------------------------------------------------------
//
//     ***     AUTO GENERATED CODE    ***    Type: MMv1     ***
//
// ----------------------------------------------------------------------------
//
//     This file is automatically generated by Magic Modules and manual
//     changes will be clobbered when the file is regenerated.
//
//     Please read more about how to change this file in
//     .github/CONTRIBUTING.md.
//
// ----------------------------------------------------------------------------

package iambeta_test

import (
	"os"
	"testing"

	"github.com/GoogleCloudPlatform/terraform-google-conversion/v7/test"
)

func TestAccIAMBetaWorkloadIdentityPoolProvider(t *testing.T) {
	if os.Getenv("WRITE_FILES") != "" {
		t.Parallel()
	}
	tests := []test.TestCase{
		{
			Name: "TestAccIAMBetaWorkloadIdentityPoolProvider_iamWorkloadIdentityPoolProviderAwsBasicExample",
			Skip: "",
		},
		{
			Name: "TestAccIAMBetaWorkloadIdentityPoolProvider_iamWorkloadIdentityPoolProviderAwsFullExample",
			Skip: "",
		},
		{
			Name: "TestAccIAMBetaWorkloadIdentityPoolProvider_iamWorkloadIdentityPoolProviderGithubActionsExample",
			Skip: "",
		},
		{
			Name: "TestAccIAMBetaWorkloadIdentityPoolProvider_iamWorkloadIdentityPoolProviderOidcBasicExample",
			Skip: "",
		},
		{
			Name: "TestAccIAMBetaWorkloadIdentityPoolProvider_iamWorkloadIdentityPoolProviderOidcFullExample",
			Skip: "",
		},
		{
			Name: "TestAccIAMBetaWorkloadIdentityPoolProvider_iamWorkloadIdentityPoolProviderSamlBasicExample",
			Skip: "",
		},
		{
			Name: "TestAccIAMBetaWorkloadIdentityPoolProvider_iamWorkloadIdentityPoolProviderSamlFullExample",
			Skip: "",
		},
		{
			Name: "TestAccIAMBetaWorkloadIdentityPoolProvider_iamWorkloadIdentityPoolProviderOidcUploadKeyExample",
			Skip: "",
		},
		{
			Name: "TestAccIAMBetaWorkloadIdentityPoolProvider_iamWorkloadIdentityPoolProviderX509BasicExample",
			Skip: "",
		},
		{
			Name: "TestAccIAMBetaWorkloadIdentityPoolProvider_iamWorkloadIdentityPoolProviderX509FullExample",
			Skip: "",
		},
	}

	for _, tt := range tests {
		tt := tt

		t.Run(tt.Name, func(t *testing.T) {
			t.Parallel()

			if tt.Skip != "" {
				t.Skipf("Skipping %s test case: This case is currently disabled due to Issue.", tt.Name)
			}

			test.BidirectionalConversion(
				t,
				[]string{
					"count",
					"depends_on",
					"for_each",
					"lifecycle",
					"oidc.jwks_json",
					"provider",
					"workload_identity_pool_id",
					"workload_identity_pool_provider_id",
				},
				"google_iam_workload_identity_pool_provider",
			)
		})
	}
}
