// ----------------------------------------------------------------------------
//
//     ***     AUTO GENERATED CODE    ***    Type: MMv1     ***
//
// ----------------------------------------------------------------------------
//
//     This file is automatically generated by Magic Modules and manual
//     changes will be clobbered when the file is regenerated.
//
//     Please read more about how to change this file in
//     .github/CONTRIBUTING.md.
//
// ----------------------------------------------------------------------------

package vmwareengine_test

import (
	"testing"

	"github.com/GoogleCloudPlatform/terraform-google-conversion/v7/test"
)

func TestAccVmwareengineNetworkPolicy_vmwareEngineNetworkPolicyBasicExample(t *testing.T) {
	t.Parallel()

	test.BidirectionalConversion(
		t,
		[]string{
			"count",
			"depends_on",
			"for_each",
			"lifecycle",
			"location",
			"name",
			"provider",
		},
	)
}
func TestAccVmwareengineNetworkPolicy_vmwareEngineNetworkPolicyFullExample(t *testing.T) {
	t.Parallel()

	test.BidirectionalConversion(
		t,
		[]string{
			"count",
			"depends_on",
			"for_each",
			"lifecycle",
			"location",
			"name",
			"provider",
		},
	)
}
func TestAccVmwareengineNetworkPolicy_update(t *testing.T) {
	t.Parallel()

	test.BidirectionalConversion(
		t,
		[]string{
			"count",
			"depends_on",
			"for_each",
			"lifecycle",
			"location",
			"name",
			"provider",
		},
	)
}
