// ----------------------------------------------------------------------------
//
//     ***     AUTO GENERATED CODE    ***    Type: MMv1     ***
//
// ----------------------------------------------------------------------------
//
//     This file is automatically generated by Magic Modules and manual
//     changes will be clobbered when the file is regenerated.
//
//     Please read more about how to change this file in
//     .github/CONTRIBUTING.md.
//
// ----------------------------------------------------------------------------

// Package biglakeiceberg contains resources, datasources, etc. for the biglake service.
package biglakeiceberg

import (
	"github.com/GoogleCloudPlatform/terraform-google-conversion/v7/pkg/registry"
)

const ProductName = "biglakeiceberg"

func init() {
	registry.Product{
		Name:    "biglakeiceberg",
		BaseUrl: "https://biglake.googleapis.com/",
	}.Register()
}
