// ----------------------------------------------------------------------------
//
//     ***     AUTO GENERATED CODE    ***    AUTO GENERATED CODE     ***
//
// ----------------------------------------------------------------------------
//
//     This file is automatically generated by Magic Modules and manual
//     changes will be clobbered when the file is regenerated.
//
//     Please read more about how to change this file in
//     .github/CONTRIBUTING.md.
//
// ----------------------------------------------------------------------------

package google

import "fmt"

func GetNotebooksInstanceIamPolicyCaiObject(d TerraformResourceData, config *Config) ([]Asset, error) {
	return newNotebooksInstanceIamAsset(d, config, expandIamPolicyBindings)
}

func GetNotebooksInstanceIamBindingCaiObject(d TerraformResourceData, config *Config) ([]Asset, error) {
	return newNotebooksInstanceIamAsset(d, config, expandIamRoleBindings)
}

func GetNotebooksInstanceIamMemberCaiObject(d TerraformResourceData, config *Config) ([]Asset, error) {
	return newNotebooksInstanceIamAsset(d, config, expandIamMemberBindings)
}

func MergeNotebooksInstanceIamPolicy(existing, incoming Asset) Asset {
	existing.IAMPolicy = incoming.IAMPolicy
	return existing
}

func MergeNotebooksInstanceIamBinding(existing, incoming Asset) Asset {
	return mergeIamAssets(existing, incoming, mergeAuthoritativeBindings)
}

func MergeNotebooksInstanceIamBindingDelete(existing, incoming Asset) Asset {
	return mergeDeleteIamAssets(existing, incoming, mergeDeleteAuthoritativeBindings)
}

func MergeNotebooksInstanceIamMember(existing, incoming Asset) Asset {
	return mergeIamAssets(existing, incoming, mergeAdditiveBindings)
}

func MergeNotebooksInstanceIamMemberDelete(existing, incoming Asset) Asset {
	return mergeDeleteIamAssets(existing, incoming, mergeDeleteAdditiveBindings)
}

func newNotebooksInstanceIamAsset(
	d TerraformResourceData,
	config *Config,
	expandBindings func(d TerraformResourceData) ([]IAMBinding, error),
) ([]Asset, error) {
	bindings, err := expandBindings(d)
	if err != nil {
		return []Asset{}, fmt.Errorf("expanding bindings: %v", err)
	}

	name, err := assetName(d, config, "//notebooks.googleapis.com/{{instance}}")
	if err != nil {
		return []Asset{}, err
	}

	return []Asset{{
		Name: name,
		Type: "notebooks.googleapis.com/Instance",
		IAMPolicy: &IAMPolicy{
			Bindings: bindings,
		},
	}}, nil
}

func FetchNotebooksInstanceIamPolicy(d TerraformResourceData, config *Config) (Asset, error) {
	// Check if the identity field returns a value
	if _, ok := d.GetOk("{{instance}}"); !ok {
		return Asset{}, ErrEmptyIdentityField
	}

	return fetchIamPolicy(
		NotebooksInstanceIamUpdaterProducer,
		d,
		config,
		"//notebooks.googleapis.com/{{instance}}",
		"notebooks.googleapis.com/Instance",
	)
}
