// ----------------------------------------------------------------------------
//
//     ***     AUTO GENERATED CODE    ***    Type: MMv1     ***
//
// ----------------------------------------------------------------------------
//
//     This file is automatically generated by Magic Modules and manual
//     changes will be clobbered when the file is regenerated.
//
//     Please read more about how to change this file in
//     .github/CONTRIBUTING.md.
//
// ----------------------------------------------------------------------------

package bigquery

import (
	"fmt"

	"github.com/GoogleCloudPlatform/terraform-google-conversion/v2/tfplan2cai/converters/google/resources/cai"
	"github.com/hashicorp/terraform-provider-google-beta/google-beta/tpgresource"
	transport_tpg "github.com/hashicorp/terraform-provider-google-beta/google-beta/transport"
)

// Provide a separate asset type constant so we don't have to worry about name conflicts between IAM and non-IAM converter files
const BigQueryTableIAMAssetType string = "bigquery.googleapis.com/Table"

func ResourceConverterBigQueryTableIamPolicy() cai.ResourceConverter {
	return cai.ResourceConverter{
		AssetType:         BigQueryTableIAMAssetType,
		Convert:           GetBigQueryTableIamPolicyCaiObject,
		MergeCreateUpdate: MergeBigQueryTableIamPolicy,
	}
}

func ResourceConverterBigQueryTableIamBinding() cai.ResourceConverter {
	return cai.ResourceConverter{
		AssetType:         BigQueryTableIAMAssetType,
		Convert:           GetBigQueryTableIamBindingCaiObject,
		FetchFullResource: FetchBigQueryTableIamPolicy,
		MergeCreateUpdate: MergeBigQueryTableIamBinding,
		MergeDelete:       MergeBigQueryTableIamBindingDelete,
	}
}

func ResourceConverterBigQueryTableIamMember() cai.ResourceConverter {
	return cai.ResourceConverter{
		AssetType:         BigQueryTableIAMAssetType,
		Convert:           GetBigQueryTableIamMemberCaiObject,
		FetchFullResource: FetchBigQueryTableIamPolicy,
		MergeCreateUpdate: MergeBigQueryTableIamMember,
		MergeDelete:       MergeBigQueryTableIamMemberDelete,
	}
}

func GetBigQueryTableIamPolicyCaiObject(d tpgresource.TerraformResourceData, config *transport_tpg.Config) ([]cai.Asset, error) {
	return newBigQueryTableIamAsset(d, config, cai.ExpandIamPolicyBindings)
}

func GetBigQueryTableIamBindingCaiObject(d tpgresource.TerraformResourceData, config *transport_tpg.Config) ([]cai.Asset, error) {
	return newBigQueryTableIamAsset(d, config, cai.ExpandIamRoleBindings)
}

func GetBigQueryTableIamMemberCaiObject(d tpgresource.TerraformResourceData, config *transport_tpg.Config) ([]cai.Asset, error) {
	return newBigQueryTableIamAsset(d, config, cai.ExpandIamMemberBindings)
}

func MergeBigQueryTableIamPolicy(existing, incoming cai.Asset) cai.Asset {
	existing.IAMPolicy = incoming.IAMPolicy
	return existing
}

func MergeBigQueryTableIamBinding(existing, incoming cai.Asset) cai.Asset {
	return cai.MergeIamAssets(existing, incoming, cai.MergeAuthoritativeBindings)
}

func MergeBigQueryTableIamBindingDelete(existing, incoming cai.Asset) cai.Asset {
	return cai.MergeDeleteIamAssets(existing, incoming, cai.MergeDeleteAuthoritativeBindings)
}

func MergeBigQueryTableIamMember(existing, incoming cai.Asset) cai.Asset {
	return cai.MergeIamAssets(existing, incoming, cai.MergeAdditiveBindings)
}

func MergeBigQueryTableIamMemberDelete(existing, incoming cai.Asset) cai.Asset {
	return cai.MergeDeleteIamAssets(existing, incoming, cai.MergeDeleteAdditiveBindings)
}

func newBigQueryTableIamAsset(
	d tpgresource.TerraformResourceData,
	config *transport_tpg.Config,
	expandBindings func(d tpgresource.TerraformResourceData) ([]cai.IAMBinding, error),
) ([]cai.Asset, error) {
	bindings, err := expandBindings(d)
	if err != nil {
		return []cai.Asset{}, fmt.Errorf("expanding bindings: %v", err)
	}

	name, err := cai.AssetName(d, config, "//bigquery.googleapis.com/projects/{{project}}/datasets/{{dataset_id}}/tables/{{table_id}}")
	if err != nil {
		return []cai.Asset{}, err
	}

	return []cai.Asset{{
		Name: name,
		Type: BigQueryTableIAMAssetType,
		IAMPolicy: &cai.IAMPolicy{
			Bindings: bindings,
		},
	}}, nil
}

func FetchBigQueryTableIamPolicy(d tpgresource.TerraformResourceData, config *transport_tpg.Config) (cai.Asset, error) {
	// Check if the identity field returns a value
	if _, ok := d.GetOk("dataset_id"); !ok {
		return cai.Asset{}, cai.ErrEmptyIdentityField
	}
	if _, ok := d.GetOk("table_id"); !ok {
		return cai.Asset{}, cai.ErrEmptyIdentityField
	}

	return cai.FetchIamPolicy(
		BigQueryTableIamUpdaterProducer,
		d,
		config,
		"//bigquery.googleapis.com/projects/{{project}}/datasets/{{dataset_id}}/tables/{{table_id}}",
		BigQueryTableIAMAssetType,
	)
}
