// ----------------------------------------------------------------------------
//
//     ***     AUTO GENERATED CODE    ***    Type: MMv1     ***
//
// ----------------------------------------------------------------------------
//
//     This file is automatically generated by Magic Modules and manual
//     changes will be clobbered when the file is regenerated.
//
//     Please read more about how to change this file in
//     .github/CONTRIBUTING.md.
//
// ----------------------------------------------------------------------------

package secretmanager_test

import (
	"testing"

	"github.com/GoogleCloudPlatform/terraform-google-conversion/v7/test"
)

func TestAccSecretManagerSecretVersion_secretVersionBasicExample(t *testing.T) {
	t.Parallel()

	test.BidirectionalConversion(
		t,
		[]string{
			"count",
			"deletion_policy",
			"depends_on",
			"for_each",
			"is_secret_data_base64",
			"lifecycle",
			"provider",
			"secret",
			"secret_data",
			"secret_data_wo",
			"secret_data_wo_version",
		},
	)
}
func TestAccSecretManagerSecretVersion_secretVersionBasicWriteOnlyExample(t *testing.T) {
	t.Parallel()

	test.BidirectionalConversion(
		t,
		[]string{
			"count",
			"deletion_policy",
			"depends_on",
			"for_each",
			"is_secret_data_base64",
			"lifecycle",
			"provider",
			"secret",
			"secret_data",
			"secret_data_wo",
			"secret_data_wo_version",
		},
	)
}
func TestAccSecretManagerSecretVersion_secretVersionDeletionPolicyAbandonExample(t *testing.T) {
	t.Parallel()

	test.BidirectionalConversion(
		t,
		[]string{
			"count",
			"deletion_policy",
			"depends_on",
			"for_each",
			"is_secret_data_base64",
			"lifecycle",
			"provider",
			"secret",
			"secret_data",
			"secret_data_wo",
			"secret_data_wo_version",
		},
	)
}
func TestAccSecretManagerSecretVersion_secretVersionDeletionPolicyDisableExample(t *testing.T) {
	t.Parallel()

	test.BidirectionalConversion(
		t,
		[]string{
			"count",
			"deletion_policy",
			"depends_on",
			"for_each",
			"is_secret_data_base64",
			"lifecycle",
			"provider",
			"secret",
			"secret_data",
			"secret_data_wo",
			"secret_data_wo_version",
		},
	)
}
func TestAccSecretManagerSecretVersion_secretVersionWithBase64StringSecretDataExample(t *testing.T) {
	t.Parallel()

	test.BidirectionalConversion(
		t,
		[]string{
			"count",
			"deletion_policy",
			"depends_on",
			"for_each",
			"is_secret_data_base64",
			"lifecycle",
			"provider",
			"secret",
			"secret_data",
			"secret_data_wo",
			"secret_data_wo_version",
		},
	)
}
func TestAccSecretManagerSecretVersion_secretVersionWithBase64StringSecretDataWriteOnlyExample(t *testing.T) {
	t.Parallel()

	test.BidirectionalConversion(
		t,
		[]string{
			"count",
			"deletion_policy",
			"depends_on",
			"for_each",
			"is_secret_data_base64",
			"lifecycle",
			"provider",
			"secret",
			"secret_data",
			"secret_data_wo",
			"secret_data_wo_version",
		},
	)
}
