// ----------------------------------------------------------------------------
//
//     ***     AUTO GENERATED CODE    ***    Type: MMv1     ***
//
// ----------------------------------------------------------------------------
//
//     This file is automatically generated by Magic Modules and manual
//     changes will be clobbered when the file is regenerated.
//
//     Please read more about how to change this file in
//     .github/CONTRIBUTING.md.
//
// ----------------------------------------------------------------------------

package networksecurity_test

import (
	"testing"

	"github.com/GoogleCloudPlatform/terraform-google-conversion/v7/test"
)

func TestAccNetworkSecuritySecurityProfile_networkSecuritySecurityProfileBasicExample(t *testing.T) {
	t.Parallel()

	test.BidirectionalConversion(
		t,
		[]string{
			"count",
			"depends_on",
			"for_each",
			"lifecycle",
			"location",
			"name",
			"parent",
			"provider",
			"url_filtering_profile",
		},
		[]string{},
	)
}
func TestAccNetworkSecuritySecurityProfile_networkSecuritySecurityProfileOverridesExample(t *testing.T) {
	t.Parallel()

	test.BidirectionalConversion(
		t,
		[]string{
			"count",
			"depends_on",
			"for_each",
			"lifecycle",
			"location",
			"name",
			"parent",
			"provider",
			"url_filtering_profile",
		},
		[]string{},
	)
}
func TestAccNetworkSecuritySecurityProfile_networkSecuritySecurityProfileMirroringExample(t *testing.T) {
	t.Parallel()

	test.BidirectionalConversion(
		t,
		[]string{
			"count",
			"depends_on",
			"for_each",
			"lifecycle",
			"location",
			"name",
			"parent",
			"provider",
			"url_filtering_profile",
		},
		[]string{},
	)
}
func TestAccNetworkSecuritySecurityProfile_networkSecuritySecurityProfileInterceptExample(t *testing.T) {
	t.Parallel()

	test.BidirectionalConversion(
		t,
		[]string{
			"count",
			"depends_on",
			"for_each",
			"lifecycle",
			"location",
			"name",
			"parent",
			"provider",
			"url_filtering_profile",
		},
		[]string{},
	)
}
func TestAccNetworkSecuritySecurityProfile_networkSecuritySecurityProfileUrlFilteringExample(t *testing.T) {
	t.Skip("The ENUM value URL_FILTERING in type field is transformed to UNKNOWN_ENUM_VALUE_ProfileType_5 in CAI asset. The reason could be that URL_FILTERING is not supported in CAI yet. Will check if the value in CAI assets will be correct later.")
	t.Parallel()

	test.BidirectionalConversion(
		t,
		[]string{
			"count",
			"depends_on",
			"for_each",
			"lifecycle",
			"location",
			"name",
			"parent",
			"provider",
			"url_filtering_profile",
		},
		[]string{},
	)
}
